image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

services:
    - docker

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - docker-compose up &
  - sleep 240
  - java -jar ./artifacts/app-deadline.jar &
  - chmod +x gradlew

build_script:
- ./gradlew test --info -Dselenide.headless=true
